### ISSUE TITLE
Is it possible to run this in SSR?

### ISSUE THREAD

**Issue by digitalit** [gammpamm/plasma-nuxt#1]
Is it possible to run this in SSR and not as SPA?

Thank you.

**Comment by gammpamm** [comment]
This project only SPA tested. But i work on an new project with SSR.

The best way, is to split Nuxt and Andonis in two differrent projects. You can set the mode from SPA to universal in the nuxt config. Over yarn generate you can create the files for static hosting with SSR prerendered pages.

Here is a good explanation:
https://www.udemy.com/nuxtjs-vuejs-on-steroids/
The free preview video: What can we Build with Nuxt?

**Comment by digitalit** [comment]
Interesting.

Yes i had Nuxt.js as client and Adonis API only as server with proxy but i need to run my projects in Plesk and i couldn't get Nuxt running without a start file like server.js so i had to use Adonuxt.

Yes i have bought Maximillians great courses.

Thank you.
