### ISSUE TITLE
RefreshToken does not works

### ISSUE THREAD

**Issue by pirmax** [gammpamm/plasma-nuxt#2]
Hi @gammpamm,

I use your beautifull code :)

But, I have a problem with **RefreshToken**.
The token JWT is set in **localStorage**, it's present on web browser but it's expired.
I have the impression it's not go to **$axios.onResponse()** in _axios.js_ plugin.

How I can refresh the token before access auth page?

Thanks.

**Comment by pirmax** [comment]
Nobody to reply? @gammpamm

**Comment by gammpamm** [comment]
Hi @pirmax,

sorry for the late answer. What Version of @adonisjs/framework you are using?
v4.0.31 or newer?

You can show in the browser devtools console in the networktab what statuscode adonis send on expired token. If not statuscode 266, then the exception handler in adonis not working.

On newer Version on adonisjs/framework i have rewritten the expection handler from hooks.js to own custom exceptionhandler: https://gist.github.com/gammpamm/3c6a4b51b2b3357a6494ab631ca0f586

**Comment by pirmax** [comment]
I'm using the last commit of your repository.

**Comment by gammpamm** [comment]
Ok i check again and create a bugfix.

**Comment by pirmax** [comment]
With your GIST patch, it works!

**Comment by gammpamm** [comment]
Ok thx, i make a update on this repo.

**Comment by pirmax** [comment]
Thank you for your work!
